import type { ProviderGuide } from "../types";

export const kickSetupGuide: ProviderGuide = {
  provider: "kick",
  title: "Connect Kick",
  summary: "Connect Kick using its official OAuth and webhook APIs.",
  requirements: [
    "A Kick developer application with Client ID and Client Secret",
    "The temporary HTTPS webhook URL generated by StreamKit",
  ],
  docsUrl: "https://kick.com/settings/developer",
  steps: [
    {
      title: "Create and configure the Kick application",
      description:
        "Inside Settings > Developer, create a new application, add the Redirect URL and Webhook URL provided by StreamKit, enable all scopes, create the application, and copy the Client ID and Client Secret.",
      actionLabel: "Open Kick developer portal",
      actionUrl: "https://kick.com/settings/developer",
      imageUrl: "/assets/provider-guides/kick-step-1.png",
    },
  ],
};
