import type { ProviderGuide } from "../types";

export const kickSetupGuide: ProviderGuide = {
  provider: "kick",
  title: "Connect Kick",
  summary: "Connect Kick using its official OAuth and webhook APIs.",
  requirements: [
    "A Kick developer application with Client ID and Client Secret",
    "The temporary HTTPS webhook URL generated by StreamKit",
  ],
  docsUrl: "https://kick.com/settings/developer",
  steps: [
    {
      title: "Create a Kick developer application",
      description:
        "Open Settings > Developer and create a new application. Add the Redirect URL and Webhook URL provided by StreamKit, enable the required scopes, create the application, and copy the Client ID and Client Secret.",
      actionLabel: "Open Kick developer portal",
      actionUrl: "https://kick.com/settings/developer",
    },
    {
      title: "Enter the application credentials",
      description:
        "Copy the Client ID and Client Secret into the secure fields below. StreamKit will reuse the URLs already registered in Kick and open the official authorization page.",
    },
  ],
};
