import type { ProviderGuide } from "../types";

export const kickSetupGuide: ProviderGuide = {
  provider: "kick",
  title: "Connect Kick",
  summary: "Connect Kick using its official OAuth and webhook APIs.",
  requirements: [
    "A Kick developer application with Client ID and Client Secret",
    "The temporary HTTPS webhook URL generated by StreamKit",
  ],
  docsUrl: "https://docs.kick.com/",
  steps: [
    {
      title: "Create a Kick developer application",
      description:
        "Open the Kick developer portal and create an application. The Redirect URL and temporary HTTPS Webhook URL are shown in this guide as soon as it opens. Register both values in the application before copying credentials.",
      actionLabel: "Open Kick developer portal",
      actionUrl: "https://dev.kick.com/",
    },
    {
      title: "Enter the application credentials",
      description:
        "Copy the Client ID and Client Secret into the secure fields below. StreamKit will reuse the URLs already registered in Kick and open the official authorization page. Request only user:read, channel:read, chat:write, events:subscribe, moderation:ban, and chat moderation permissions.",
    },
  ],
};
